/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateAgentRequest,
  CreateUserRequest,
  GetDashboardAlertsParams,
  GetDashboardTrendParams,
  GetLogListParams,
  GetProcessListParams,
  GetServerListParams,
  LoginRequest,
  UpdateAgentRequest,
  UpdateUserRequest,
  WebhookConfigUpdate
} from './model';

import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  AgentStatus,
  AgentTarget,
  AlertItem,
  DashboardMetrics,
  DashboardTrend,
  DeploymentHistoryItem,
  DeploymentItem,
  HostInfo,
  LoginResponse,
  MeResponse,
  PagedResultLogItem,
  PagedResultServerItem,
  ProcessDetail,
  ProcessItem,
  ServerDetail,
  TestWebhookConfig200,
  UserItem,
  WebhookConfig
} from './model';

export const getDevOpsDashboardAPI = () => {
/**
 * 使用用户名密码登录，返回 JWT Token、用户信息和权限点列表
 * @summary 用户登录
 */
const login = <TData = AxiosResponse<LoginResponse>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/login`,
      loginRequest,options
    );
  }

/**
 * 返回当前登录用户信息及权限点列表（前端按钮/菜单级权限控制依据）
 * @summary 获取当前用户信息
 */
const getMe = <TData = AxiosResponse<MeResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/auth/me`,options
    );
  }

/**
 * 使当前 Token 失效（客户端清空本地状态即可，服务端尽力处理）
 * @summary 退出登录
 */
const logout = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/logout`,undefined,options
    );
  }

/**
 * 返回本机实时的 CPU、内存、磁盘使用率及当前告警数（通过 gopsutil 采集）
 * @summary 获取仪表盘当前核心指标
 */
const getDashboardMetrics = <TData = AxiosResponse<DashboardMetrics>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/dashboard/metrics`,options
    );
  }

/**
 * 返回最近 N 小时内本机 CPU 和内存使用率的时序数据（后端定时采集）
 * @summary 获取仪表盘趋势数据
 */
const getDashboardTrend = <TData = AxiosResponse<DashboardTrend>>(
    params?: GetDashboardTrendParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/dashboard/trend`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 返回最近的系统告警，默认 Top 5
 * @summary 获取最近告警列表
 */
const getDashboardAlerts = <TData = AxiosResponse<AlertItem[]>>(
    params?: GetDashboardAlertsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/dashboard/alerts`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 分页获取服务器资产列表，支持按状态筛选
 * @summary 获取服务器列表
 */
const getServerList = <TData = AxiosResponse<PagedResultServerItem>>(
    params?: GetServerListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/servers`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 根据 ID 获取单台服务器的详细信息（含磁盘、网卡）
 * @summary 获取服务器详情
 */
const getServerDetail = <TData = AxiosResponse<ServerDetail>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/servers/${id}`,options
    );
  }

/**
 * 分页获取系统日志，支持按级别筛选和关键词搜索
 * @summary 获取日志列表
 */
const getLogList = <TData = AxiosResponse<PagedResultLogItem>>(
    params?: GetLogListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/logs`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 获取所有应用的部署状态概览
 * @summary 获取应用部署列表
 */
const getDeploymentList = <TData = AxiosResponse<DeploymentItem[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/deployments`,options
    );
  }

/**
 * 获取某个应用的最近部署记录
 * @summary 获取应用部署历史
 */
const getDeploymentHistory = <TData = AxiosResponse<DeploymentHistoryItem[]>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/deployments/${id}/history`,options
    );
  }

/**
 * 返回当前运行中的进程列表，支持按 CPU/内存排序和进程名搜索
 * @summary 获取本机进程列表
 */
const getProcessList = <TData = AxiosResponse<ProcessItem[]>>(
    params?: GetProcessListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/monitor/processes`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 根据 PID 获取单个进程的详细资源占用和状态
 * @summary 获取进程详情
 */
const getProcessDetail = <TData = AxiosResponse<ProcessDetail>>(
    pid: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/monitor/processes/${pid}`,options
    );
  }

/**
 * 返回本机的操作系统、CPU、内存、启动时间等硬件信息
 * @summary 获取主机信息
 */
const getHostInfo = <TData = AxiosResponse<HostInfo>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/monitor/host`,options
    );
  }

/**
 * 返回当前告警推送配置（钉钉/企业微信机器人），secret 密钥不回传
 * @summary 获取告警 Webhook 配置
 */
const getWebhookConfig = <TData = AxiosResponse<WebhookConfig>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/settings/webhook`,options
    );
  }

/**
 * 更新推送开关、渠道类型、Webhook 地址。保存后热生效（重建 Notifier）。
 * @summary 更新告警 Webhook 配置
 */
const updateWebhookConfig = <TData = AxiosResponse<WebhookConfig>>(
    webhookConfigUpdate: WebhookConfigUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/settings/webhook`,
      webhookConfigUpdate,options
    );
  }

/**
 * 按当前配置向目标 URL 发送一条测试告警消息，用于验证渠道连通性
 * @summary 发送测试告警到 Webhook
 */
const testWebhookConfig = <TData = AxiosResponse<TestWebhookConfig200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/settings/webhook/test`,undefined,options
    );
  }

/**
 * 返回所有已配置的 Agent 分发目标
 * @summary 获取 Agent 目标列表
 */
const getAgentList = <TData = AxiosResponse<AgentTarget[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/agents`,options
    );
  }

/**
 * 创建新的 Agent 分发目标（密码仅入站，不存储明文序列化）
 * @summary 新增 Agent 目标
 */
const createAgent = <TData = AxiosResponse<AgentTarget>>(
    createAgentRequest: CreateAgentRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/agents`,
      createAgentRequest,options
    );
  }

/**
 * 更新指定 Agent 的配置（密码留空表示不修改）
 * @summary 更新 Agent 目标
 */
const updateAgent = <TData = AxiosResponse<AgentTarget>>(
    id: string,
    updateAgentRequest: UpdateAgentRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/agents/${id}`,
      updateAgentRequest,options
    );
  }

/**
 * @summary 删除 Agent 目标
 */
const deleteAgent = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/agents/${id}`,options
    );
  }

/**
 * 通过 SSH 将 Agent 二进制部署到目标服务器
 * @summary 部署 Agent 到目标机
 */
const deployAgent = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/agents/${id}/deploy`,undefined,options
    );
  }

/**
 * @summary 停止目标机上的 Agent
 */
const stopAgent = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/agents/${id}/stop`,undefined,options
    );
  }

/**
 * @summary 检查 Agent 运行状态
 */
const checkAgentStatus = <TData = AxiosResponse<AgentStatus>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/agents/${id}/status`,options
    );
  }

/**
 * @summary 获取用户列表（仅管理员）
 */
const getUserList = <TData = AxiosResponse<UserItem[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/users`,options
    );
  }

/**
 * 创建新用户，密码仅出现在请求中
 * @summary 新增用户（仅管理员）
 */
const createUser = <TData = AxiosResponse<UserItem>>(
    createUserRequest: CreateUserRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/users`,
      createUserRequest,options
    );
  }

/**
 * 更新用户角色或密码（密码留空表示不修改）
 * @summary 更新用户（仅管理员）
 */
const updateUser = <TData = AxiosResponse<UserItem>>(
    id: string,
    updateUserRequest: UpdateUserRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/users/${id}`,
      updateUserRequest,options
    );
  }

/**
 * @summary 删除用户（仅管理员）
 */
const deleteUser = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/users/${id}`,options
    );
  }

return {login,getMe,logout,getDashboardMetrics,getDashboardTrend,getDashboardAlerts,getServerList,getServerDetail,getLogList,getDeploymentList,getDeploymentHistory,getProcessList,getProcessDetail,getHostInfo,getWebhookConfig,updateWebhookConfig,testWebhookConfig,getAgentList,createAgent,updateAgent,deleteAgent,deployAgent,stopAgent,checkAgentStatus,getUserList,createUser,updateUser,deleteUser}};
export type LoginResult = AxiosResponse<LoginResponse>
export type GetMeResult = AxiosResponse<MeResponse>
export type LogoutResult = AxiosResponse<void>
export type GetDashboardMetricsResult = AxiosResponse<DashboardMetrics>
export type GetDashboardTrendResult = AxiosResponse<DashboardTrend>
export type GetDashboardAlertsResult = AxiosResponse<AlertItem[]>
export type GetServerListResult = AxiosResponse<PagedResultServerItem>
export type GetServerDetailResult = AxiosResponse<ServerDetail>
export type GetLogListResult = AxiosResponse<PagedResultLogItem>
export type GetDeploymentListResult = AxiosResponse<DeploymentItem[]>
export type GetDeploymentHistoryResult = AxiosResponse<DeploymentHistoryItem[]>
export type GetProcessListResult = AxiosResponse<ProcessItem[]>
export type GetProcessDetailResult = AxiosResponse<ProcessDetail>
export type GetHostInfoResult = AxiosResponse<HostInfo>
export type GetWebhookConfigResult = AxiosResponse<WebhookConfig>
export type UpdateWebhookConfigResult = AxiosResponse<WebhookConfig>
export type TestWebhookConfigResult = AxiosResponse<TestWebhookConfig200>
export type GetAgentListResult = AxiosResponse<AgentTarget[]>
export type CreateAgentResult = AxiosResponse<AgentTarget>
export type UpdateAgentResult = AxiosResponse<AgentTarget>
export type DeleteAgentResult = AxiosResponse<void>
export type DeployAgentResult = AxiosResponse<void>
export type StopAgentResult = AxiosResponse<void>
export type CheckAgentStatusResult = AxiosResponse<AgentStatus>
export type GetUserListResult = AxiosResponse<UserItem[]>
export type CreateUserResult = AxiosResponse<UserItem>
export type UpdateUserResult = AxiosResponse<UserItem>
export type DeleteUserResult = AxiosResponse<void>


export const getLoginResponseMock = (overrideResponse: Partial< LoginResponse > = {}): LoginResponse => ({token: faker.string.alpha({length: {min: 10, max: 20}}), user: {id: faker.string.alpha({length: {min: 10, max: 20}}), username: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['admin','operator','viewer'] as const), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined])}, permissions: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), ...overrideResponse})

export const getGetMeResponseMock = (overrideResponse: Partial< MeResponse > = {}): MeResponse => ({user: {id: faker.string.alpha({length: {min: 10, max: 20}}), username: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['admin','operator','viewer'] as const), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined])}, permissions: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), ...overrideResponse})

export const getGetDashboardMetricsResponseMock = (overrideResponse: Partial< DashboardMetrics > = {}): DashboardMetrics => ({cpu: {current: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), status: faker.helpers.arrayElement(['normal','warning','critical'] as const)}, memory: {current: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), status: faker.helpers.arrayElement(['normal','warning','critical'] as const)}, disk: {current: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), status: faker.helpers.arrayElement(['normal','warning','critical'] as const)}, alertCount: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getGetDashboardTrendResponseMock = (overrideResponse: Partial< DashboardTrend > = {}): DashboardTrend => ({timeLabels: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), cpuData: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), memoryData: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), ...overrideResponse})

export const getGetDashboardAlertsResponseMock = (): AlertItem[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), level: faker.helpers.arrayElement(['info','warning','critical'] as const), message: faker.string.alpha({length: {min: 10, max: 20}}), source: faker.string.alpha({length: {min: 10, max: 20}}), time: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getGetServerListResponseMock = (overrideResponse: Partial< PagedResultServerItem > = {}): PagedResultServerItem => ({list: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), hostname: faker.string.alpha({length: {min: 10, max: 20}}), ip: faker.string.alpha({length: {min: 10, max: 20}}), os: faker.string.alpha({length: {min: 10, max: 20}}), cpuCores: faker.number.int({min: undefined, max: undefined}), memoryGb: faker.number.int({min: undefined, max: undefined}), status: faker.helpers.arrayElement(['running','stopped','maintenance'] as const), uptime: faker.string.alpha({length: {min: 10, max: 20}})})), total: faker.number.int({min: undefined, max: undefined}), page: faker.number.int({min: undefined, max: undefined}), pageSize: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getGetServerDetailResponseMock = (): ServerDetail => ({...{id: faker.string.alpha({length: {min: 10, max: 20}}), hostname: faker.string.alpha({length: {min: 10, max: 20}}), ip: faker.string.alpha({length: {min: 10, max: 20}}), os: faker.string.alpha({length: {min: 10, max: 20}}), cpuCores: faker.number.int({min: undefined, max: undefined}), memoryGb: faker.number.int({min: undefined, max: undefined}), status: faker.helpers.arrayElement(['running','stopped','maintenance'] as const), uptime: faker.string.alpha({length: {min: 10, max: 20}})},...{diskPartitions: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({mount: faker.string.alpha({length: {min: 10, max: 20}}), totalGb: faker.number.int({min: undefined, max: undefined}), usedGb: faker.number.int({min: undefined, max: undefined})})), networkInterfaces: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({name: faker.string.alpha({length: {min: 10, max: 20}}), ip: faker.string.alpha({length: {min: 10, max: 20}}), mac: faker.string.alpha({length: {min: 10, max: 20}})}))},})

export const getGetLogListResponseMock = (overrideResponse: Partial< PagedResultLogItem > = {}): PagedResultLogItem => ({list: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), time: `${faker.date.past().toISOString().split('.')[0]}Z`, level: faker.helpers.arrayElement(['INFO','WARN','ERROR'] as const), service: faker.string.alpha({length: {min: 10, max: 20}}), content: faker.string.alpha({length: {min: 10, max: 20}})})), total: faker.number.int({min: undefined, max: undefined}), page: faker.number.int({min: undefined, max: undefined}), pageSize: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getGetDeploymentListResponseMock = (): DeploymentItem[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), appName: faker.string.alpha({length: {min: 10, max: 20}}), version: faker.string.alpha({length: {min: 10, max: 20}}), env: faker.helpers.arrayElement(['dev','test','prod'] as const), status: faker.helpers.arrayElement(['pending','deploying','success','failed'] as const), lastDeployedAt: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getGetDeploymentHistoryResponseMock = (): DeploymentHistoryItem[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({version: faker.string.alpha({length: {min: 10, max: 20}}), operator: faker.string.alpha({length: {min: 10, max: 20}}), durationSec: faker.number.int({min: undefined, max: undefined}), status: faker.helpers.arrayElement(['success','failed'] as const), deployedAt: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getGetProcessListResponseMock = (): ProcessItem[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({pid: faker.number.int({min: undefined, max: undefined}), name: faker.string.alpha({length: {min: 10, max: 20}}), cmdline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), cpuPercent: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), memoryPercent: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), memoryMb: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), status: faker.string.alpha({length: {min: 10, max: 20}})})))

export const getGetProcessDetailResponseMock = (): ProcessDetail => ({...{pid: faker.number.int({min: undefined, max: undefined}), name: faker.string.alpha({length: {min: 10, max: 20}}), cmdline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), cpuPercent: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), memoryPercent: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), memoryMb: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), status: faker.string.alpha({length: {min: 10, max: 20}})},...{ppid: faker.number.int({min: undefined, max: undefined}), numThreads: faker.number.int({min: undefined, max: undefined}), numOpenFiles: faker.number.int({min: undefined, max: undefined}), numConnections: faker.number.int({min: undefined, max: undefined}), createTime: `${faker.date.past().toISOString().split('.')[0]}Z`, username: faker.string.alpha({length: {min: 10, max: 20}}), workingDir: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), env: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), undefined])},})

export const getGetHostInfoResponseMock = (overrideResponse: Partial< HostInfo > = {}): HostInfo => ({hostname: faker.string.alpha({length: {min: 10, max: 20}}), os: faker.string.alpha({length: {min: 10, max: 20}}), platform: faker.string.alpha({length: {min: 10, max: 20}}), platformVersion: faker.string.alpha({length: {min: 10, max: 20}}), kernelVersion: faker.string.alpha({length: {min: 10, max: 20}}), arch: faker.string.alpha({length: {min: 10, max: 20}}), bootTime: `${faker.date.past().toISOString().split('.')[0]}Z`, uptime: faker.string.alpha({length: {min: 10, max: 20}}), cpuModel: faker.string.alpha({length: {min: 10, max: 20}}), cpuCores: faker.number.int({min: undefined, max: undefined}), cpuLogicalCores: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), totalMemoryGb: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), virtualMemoryGb: faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), undefined]), ...overrideResponse})

export const getGetWebhookConfigResponseMock = (overrideResponse: Partial< WebhookConfig > = {}): WebhookConfig => ({id: faker.number.int({min: undefined, max: undefined}), enabled: faker.datatype.boolean(), kind: faker.helpers.arrayElement(['dingtalk','wecom'] as const), url: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), updatedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), ...overrideResponse})

export const getUpdateWebhookConfigResponseMock = (overrideResponse: Partial< WebhookConfig > = {}): WebhookConfig => ({id: faker.number.int({min: undefined, max: undefined}), enabled: faker.datatype.boolean(), kind: faker.helpers.arrayElement(['dingtalk','wecom'] as const), url: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), updatedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), ...overrideResponse})

export const getTestWebhookConfigResponseMock = (overrideResponse: Partial< TestWebhookConfig200 > = {}): TestWebhookConfig200 => ({success: faker.datatype.boolean(), detail: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getGetAgentListResponseMock = (): AgentTarget[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), host: faker.string.alpha({length: {min: 10, max: 20}}), port: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), username: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), authType: faker.helpers.arrayElement([faker.helpers.arrayElement(['password','key'] as const), undefined]), deployDir: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), agentPort: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), status: faker.helpers.arrayElement(['running','stopped','deploying'] as const), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined])})))

export const getCreateAgentResponseMock = (overrideResponse: Partial< AgentTarget > = {}): AgentTarget => ({id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), host: faker.string.alpha({length: {min: 10, max: 20}}), port: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), username: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), authType: faker.helpers.arrayElement([faker.helpers.arrayElement(['password','key'] as const), undefined]), deployDir: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), agentPort: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), status: faker.helpers.arrayElement(['running','stopped','deploying'] as const), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), ...overrideResponse})

export const getUpdateAgentResponseMock = (overrideResponse: Partial< AgentTarget > = {}): AgentTarget => ({id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), host: faker.string.alpha({length: {min: 10, max: 20}}), port: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), username: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), authType: faker.helpers.arrayElement([faker.helpers.arrayElement(['password','key'] as const), undefined]), deployDir: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), agentPort: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), status: faker.helpers.arrayElement(['running','stopped','deploying'] as const), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), ...overrideResponse})

export const getCheckAgentStatusResponseMock = (overrideResponse: Partial< AgentStatus > = {}): AgentStatus => ({running: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), pid: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), version: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), uptimeSec: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), ...overrideResponse})

export const getGetUserListResponseMock = (): UserItem[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), username: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['admin','operator','viewer'] as const), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined])})))

export const getCreateUserResponseMock = (overrideResponse: Partial< UserItem > = {}): UserItem => ({id: faker.string.alpha({length: {min: 10, max: 20}}), username: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['admin','operator','viewer'] as const), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), ...overrideResponse})

export const getUpdateUserResponseMock = (overrideResponse: Partial< UserItem > = {}): UserItem => ({id: faker.string.alpha({length: {min: 10, max: 20}}), username: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['admin','operator','viewer'] as const), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), ...overrideResponse})


export const getLoginMockHandler = (overrideResponse?: LoginResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<LoginResponse> | LoginResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/login', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getLoginResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetMeMockHandler = (overrideResponse?: MeResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MeResponse> | MeResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/auth/me', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMeResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getLogoutMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/logout', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getGetDashboardMetricsMockHandler = (overrideResponse?: DashboardMetrics | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DashboardMetrics> | DashboardMetrics), options?: RequestHandlerOptions) => {
  return http.get('*/api/dashboard/metrics', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDashboardMetricsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetDashboardTrendMockHandler = (overrideResponse?: DashboardTrend | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DashboardTrend> | DashboardTrend), options?: RequestHandlerOptions) => {
  return http.get('*/api/dashboard/trend', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDashboardTrendResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetDashboardAlertsMockHandler = (overrideResponse?: AlertItem[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AlertItem[]> | AlertItem[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/dashboard/alerts', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDashboardAlertsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetServerListMockHandler = (overrideResponse?: PagedResultServerItem | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PagedResultServerItem> | PagedResultServerItem), options?: RequestHandlerOptions) => {
  return http.get('*/api/servers', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetServerListResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetServerDetailMockHandler = (overrideResponse?: ServerDetail | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ServerDetail> | ServerDetail), options?: RequestHandlerOptions) => {
  return http.get('*/api/servers/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetServerDetailResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetLogListMockHandler = (overrideResponse?: PagedResultLogItem | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PagedResultLogItem> | PagedResultLogItem), options?: RequestHandlerOptions) => {
  return http.get('*/api/logs', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetLogListResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetDeploymentListMockHandler = (overrideResponse?: DeploymentItem[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DeploymentItem[]> | DeploymentItem[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/deployments', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDeploymentListResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetDeploymentHistoryMockHandler = (overrideResponse?: DeploymentHistoryItem[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DeploymentHistoryItem[]> | DeploymentHistoryItem[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/deployments/:id/history', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDeploymentHistoryResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetProcessListMockHandler = (overrideResponse?: ProcessItem[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ProcessItem[]> | ProcessItem[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/monitor/processes', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetProcessListResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetProcessDetailMockHandler = (overrideResponse?: ProcessDetail | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ProcessDetail> | ProcessDetail), options?: RequestHandlerOptions) => {
  return http.get('*/api/monitor/processes/:pid', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetProcessDetailResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetHostInfoMockHandler = (overrideResponse?: HostInfo | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<HostInfo> | HostInfo), options?: RequestHandlerOptions) => {
  return http.get('*/api/monitor/host', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetHostInfoResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetWebhookConfigMockHandler = (overrideResponse?: WebhookConfig | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<WebhookConfig> | WebhookConfig), options?: RequestHandlerOptions) => {
  return http.get('*/api/settings/webhook', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetWebhookConfigResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateWebhookConfigMockHandler = (overrideResponse?: WebhookConfig | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<WebhookConfig> | WebhookConfig), options?: RequestHandlerOptions) => {
  return http.put('*/api/settings/webhook', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateWebhookConfigResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTestWebhookConfigMockHandler = (overrideResponse?: TestWebhookConfig200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TestWebhookConfig200> | TestWebhookConfig200), options?: RequestHandlerOptions) => {
  return http.post('*/api/settings/webhook/test', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTestWebhookConfigResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetAgentListMockHandler = (overrideResponse?: AgentTarget[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AgentTarget[]> | AgentTarget[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/agents', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAgentListResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreateAgentMockHandler = (overrideResponse?: AgentTarget | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AgentTarget> | AgentTarget), options?: RequestHandlerOptions) => {
  return http.post('*/api/agents', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateAgentResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateAgentMockHandler = (overrideResponse?: AgentTarget | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<AgentTarget> | AgentTarget), options?: RequestHandlerOptions) => {
  return http.put('*/api/agents/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateAgentResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteAgentMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/agents/:id', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getDeployAgentMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/agents/:id/deploy', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getStopAgentMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/agents/:id/stop', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getCheckAgentStatusMockHandler = (overrideResponse?: AgentStatus | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AgentStatus> | AgentStatus), options?: RequestHandlerOptions) => {
  return http.get('*/api/agents/:id/status', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCheckAgentStatusResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetUserListMockHandler = (overrideResponse?: UserItem[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserItem[]> | UserItem[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/users', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetUserListResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreateUserMockHandler = (overrideResponse?: UserItem | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserItem> | UserItem), options?: RequestHandlerOptions) => {
  return http.post('*/api/users', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateUserResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateUserMockHandler = (overrideResponse?: UserItem | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<UserItem> | UserItem), options?: RequestHandlerOptions) => {
  return http.put('*/api/users/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteUserMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/users/:id', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}
export const getDevOpsDashboardAPIMock = () => [
  getLoginMockHandler(),
  getGetMeMockHandler(),
  getLogoutMockHandler(),
  getGetDashboardMetricsMockHandler(),
  getGetDashboardTrendMockHandler(),
  getGetDashboardAlertsMockHandler(),
  getGetServerListMockHandler(),
  getGetServerDetailMockHandler(),
  getGetLogListMockHandler(),
  getGetDeploymentListMockHandler(),
  getGetDeploymentHistoryMockHandler(),
  getGetProcessListMockHandler(),
  getGetProcessDetailMockHandler(),
  getGetHostInfoMockHandler(),
  getGetWebhookConfigMockHandler(),
  getUpdateWebhookConfigMockHandler(),
  getTestWebhookConfigMockHandler(),
  getGetAgentListMockHandler(),
  getCreateAgentMockHandler(),
  getUpdateAgentMockHandler(),
  getDeleteAgentMockHandler(),
  getDeployAgentMockHandler(),
  getStopAgentMockHandler(),
  getCheckAgentStatusMockHandler(),
  getGetUserListMockHandler(),
  getCreateUserMockHandler(),
  getUpdateUserMockHandler(),
  getDeleteUserMockHandler()]
