/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */

/**
 * SSH 认证方式：密码 / 密钥
 */
export type AgentAuthType = typeof AgentAuthType[keyof typeof AgentAuthType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AgentAuthType = {
  password: 'password',
  key: 'key',
} as const;
