/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */
import type { AgentAuthType } from './agentAuthType';
import type { AgentTargetStatus } from './agentTargetStatus';

export interface AgentTarget {
  id: string;
  name: string;
  host: string;
  /** SSH 端口 */
  port?: number;
  username?: string;
  authType?: AgentAuthType;
  deployDir?: string;
  /** Agent 采集服务端口 */
  agentPort?: number;
  status: AgentTargetStatus;
  createdAt: string;
  updatedAt?: string;
}
