/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */
import type { AlertThresholdMetric } from './alertThresholdMetric';

export interface AlertThreshold {
  metric: AlertThresholdMetric;
  /** warning 阈值（超过触发 warning 告警） */
  warnThreshold: number;
  /** critical 阈值（超过触发 critical 告警） */
  critThreshold: number;
  updatedAt?: string;
}
