/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */
import type { AlertLevel } from './alertLevel';

export interface Alert {
  id: number;
  level: AlertLevel;
  message: string;
  source: string;
  /** 展示格式 "01-02 15:04" */
  time: string;
  /** 落库时间（排序依据） */
  createdAt?: string;
}
