/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */
import type { AlertItemLevel } from './alertItemLevel';

export interface AlertItem {
  id: string;
  level: AlertItemLevel;
  message: string;
  /** 告警来源，如服务器 IP 或服务名 */
  source: string;
  time: string;
}
