/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */

export interface AuditLog {
  id: string;
  /** 操作人用户名 */
  actor: string;
  /** 动作枚举（role.create / role.update / role.delete / permission.update / user.create / user.update / user.delete） */
  action: string;
  /** 操作对象描述 */
  target: string;
  /** 变更详情（JSON 字符串） */
  detail: string;
  /** 操作时间 */
  createdAt: string;
}
