/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */

export interface CreateRoleRequest {
  /** 角色标识（小写字母/数字/连字符，2-32 位） */
  name: string;
  /** 角色中文名 */
  label: string;
  /** 角色说明 */
  description?: string;
}
