/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */

export interface CreateAgentRequest {
  name: string;
  host: string;
  port?: number;
  username?: string;
  authType?: string;
  /** SSH 密码（仅入站，不序列化返回） */
  password?: string;
  deployDir?: string;
  agentPort?: number;
}
