/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */

export interface DashboardTrend {
  /** 时间标签数组，如 ["14:00", "15:00"] */
  timeLabels: string[];
  /** CPU 使用率时序数据 */
  cpuData: number[];
  /** 内存使用率时序数据 */
  memoryData: number[];
}
