/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */

export type DeploymentItemEnv = typeof DeploymentItemEnv[keyof typeof DeploymentItemEnv];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeploymentItemEnv = {
  dev: 'dev',
  test: 'test',
  prod: 'prod',
} as const;
