/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */
import type { GetProcessListSortBy } from './getProcessListSortBy';
import type { GetProcessListOrder } from './getProcessListOrder';

export type GetProcessListParams = {
/**
 * 排序字段
 */
sortBy?: GetProcessListSortBy;
/**
 * 排序方向
 */
order?: GetProcessListOrder;
/**
 * 进程名关键词模糊搜索
 */
keyword?: string;
/**
 * 返回条数上限（类似 top -n）
 * @maximum 200
 */
limit?: number;
};
