/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */

export interface HostInfo {
  hostname: string;
  /** 操作系统类型 */
  os: string;
  /** 平台名称 */
  platform: string;
  platformVersion: string;
  kernelVersion: string;
  /** 架构 */
  arch: string;
  /** 系统启动时间 */
  bootTime: string;
  /** 运行时长，人工可读格式 */
  uptime: string;
  cpuModel: string;
  /** 物理核心数 */
  cpuCores: number;
  /** 逻辑核心数 */
  cpuLogicalCores?: number;
  /** 总内存 (GB) */
  totalMemoryGb: number;
  /** 虚拟内存 / 交换分区总量 (GB) */
  virtualMemoryGb?: number;
}
