/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */
import type { MetricValueStatus } from './metricValueStatus';

export interface MetricValue {
  /** 当前百分比值 */
  current: number;
  /** normal < 60, warning < 80, critical >= 80 */
  status: MetricValueStatus;
}
