/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */
import type { ServerItem } from './serverItem';

export interface PagedResultServerItem {
  list: ServerItem[];
  total: number;
  page: number;
  pageSize: number;
}
