/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */

export interface PermissionGroup {
  /** 权限点资源对象（资源分组 key） */
  obj: string;
  /** 分组中文名 */
  label: string;
  /** 该分组下的权限点（obj:act 列表） */
  permissions: string[];
}
