/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */
import type { PermissionGroupRequires } from './permissionGroupRequires';

export interface PermissionGroup {
  /** 权限点资源对象（资源分组 key） */
  obj: string;
  /** 分组中文名 */
  label: string;
  /** 该分组下的权限点（obj:act 列表） */
  permissions: string[];
  /** 组内权限点的前置依赖映射（键=权限点，值=其依赖的入口权限点）。如 webhook:update → webhook:read；无依赖的分组省略此字段 */
  requires?: PermissionGroupRequires;
}
