/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */

export type ProcessDetailAllOf = {
  /** 父进程 ID */
  ppid: number;
  /** 线程数 */
  numThreads: number;
  /** 打开的文件描述符数量 */
  numOpenFiles: number;
  /** 网络连接数 */
  numConnections: number;
  /** 进程启动时间 */
  createTime: string;
  /** 运行该进程的用户 */
  username: string;
  /** 工作目录 */
  workingDir?: string;
  /** 环境变量列表（脱敏后可返回） */
  env?: string[];
};
