/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */

export interface ProcessItem {
  /** 进程 ID */
  pid: number;
  /** 进程名 */
  name: string;
  /** 启动命令行 */
  cmdline?: string;
  /** CPU 使用率 (%) */
  cpuPercent: number;
  /** 内存占用率 (%) */
  memoryPercent: number;
  /** 占用内存大小 (MB) */
  memoryMb: number;
  /** 进程状态 */
  status: string;
}
