/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */

export interface RoleInfo {
  /** 角色标识（admin / operator / viewer） */
  name: string;
  /** 角色中文名 */
  label: string;
  /** 角色说明 */
  description: string;
  /** 是否内置角色（内置角色不可删除） */
  builtin: boolean;
  /** 是否锁定（admin 为通配策略，权限不可修改） */
  locked: boolean;
  /** 该角色当前拥有的权限点（obj:act 列表） */
  permissions: string[];
}
