/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */

export type TestWebhookConfig200 = {
  success: boolean;
  /** 发送结果详情（HTTP 状态或错误信息） */
  detail?: string;
};
