/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateRoleRequest {
  /** 角色中文名（内置角色不可修改显示名） */
  label?: string;
  /** 角色说明 */
  description?: string;
}
