/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */
import type { AgentAuthType } from './agentAuthType';

export interface UpdateAgentRequest {
  name?: string;
  host?: string;
  port?: number;
  username?: string;
  authType?: AgentAuthType;
  /** 新密码，留空表示不修改 */
  password?: string;
  deployDir?: string;
  agentPort?: number;
}
