/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */

/**
 * 角色：管理员 / 运维 / 观察者
 */
export type UserItemRole = typeof UserItemRole[keyof typeof UserItemRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserItemRole = {
  admin: 'admin',
  operator: 'operator',
  viewer: 'viewer',
} as const;
