/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */
import type { WebhookConfigUpdateKind } from './webhookConfigUpdateKind';

export interface WebhookConfigUpdate {
  /** 推送开关 */
  enabled: boolean;
  /** 渠道类型 */
  kind: WebhookConfigUpdateKind;
  /** 机器人 Webhook 地址（以 http/https 开头） */
  url: string;
  /** 加签密钥（可选，钉钉安全设置用；留空表示不修改） */
  secret?: string;
}
