/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */
import type { WebhookConfigKind } from './webhookConfigKind';

export interface WebhookConfig {
  id: number;
  /** 推送开关 */
  enabled: boolean;
  /** 渠道类型：钉钉机器人 / 企业微信机器人 */
  kind: WebhookConfigKind;
  /** 机器人 Webhook 地址 */
  url: string;
  createdAt?: string;
  updatedAt?: string;
}
