/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetDashboardAlertsParams,
  GetDashboardTrendParams,
  GetLogListParams,
  GetServerListParams
} from './model';

import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  AlertItem,
  DashboardMetrics,
  DashboardTrend,
  DeploymentHistoryItem,
  DeploymentItem,
  PagedResultLogItem,
  PagedResultServerItem,
  ServerDetail
} from './model';

export const getDevOpsDashboardAPI = () => {
/**
 * 返回 CPU、内存、磁盘、告警数的当前瞬时值
 * @summary 获取仪表盘当前核心指标
 */
const getDashboardMetrics = <TData = AxiosResponse<DashboardMetrics>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/dashboard/metrics`,options
    );
  }

/**
 * 返回最近 6 小时的 CPU 和内存使用率时序数据
 * @summary 获取仪表盘趋势数据
 */
const getDashboardTrend = <TData = AxiosResponse<DashboardTrend>>(
    params?: GetDashboardTrendParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/dashboard/trend`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 返回最近的系统告警，默认 Top 5
 * @summary 获取最近告警列表
 */
const getDashboardAlerts = <TData = AxiosResponse<AlertItem[]>>(
    params?: GetDashboardAlertsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/dashboard/alerts`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 分页获取服务器资产列表，支持按状态筛选
 * @summary 获取服务器列表
 */
const getServerList = <TData = AxiosResponse<PagedResultServerItem>>(
    params?: GetServerListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/servers`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 根据 ID 获取单台服务器的详细信息（含磁盘、网卡）
 * @summary 获取服务器详情
 */
const getServerDetail = <TData = AxiosResponse<ServerDetail>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/servers/${id}`,options
    );
  }

/**
 * 分页获取系统日志，支持按级别筛选和关键词搜索
 * @summary 获取日志列表
 */
const getLogList = <TData = AxiosResponse<PagedResultLogItem>>(
    params?: GetLogListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/logs`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 获取所有应用的部署状态概览
 * @summary 获取应用部署列表
 */
const getDeploymentList = <TData = AxiosResponse<DeploymentItem[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/deployments`,options
    );
  }

/**
 * 获取某个应用的最近部署记录
 * @summary 获取应用部署历史
 */
const getDeploymentHistory = <TData = AxiosResponse<DeploymentHistoryItem[]>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/deployments/${id}/history`,options
    );
  }

return {getDashboardMetrics,getDashboardTrend,getDashboardAlerts,getServerList,getServerDetail,getLogList,getDeploymentList,getDeploymentHistory}};
export type GetDashboardMetricsResult = AxiosResponse<DashboardMetrics>
export type GetDashboardTrendResult = AxiosResponse<DashboardTrend>
export type GetDashboardAlertsResult = AxiosResponse<AlertItem[]>
export type GetServerListResult = AxiosResponse<PagedResultServerItem>
export type GetServerDetailResult = AxiosResponse<ServerDetail>
export type GetLogListResult = AxiosResponse<PagedResultLogItem>
export type GetDeploymentListResult = AxiosResponse<DeploymentItem[]>
export type GetDeploymentHistoryResult = AxiosResponse<DeploymentHistoryItem[]>


export const getGetDashboardMetricsResponseMock = (overrideResponse: Partial< DashboardMetrics > = {}): DashboardMetrics => ({cpu: {current: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), status: faker.helpers.arrayElement(['normal','warning','critical'] as const)}, memory: {current: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), status: faker.helpers.arrayElement(['normal','warning','critical'] as const)}, disk: {current: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), status: faker.helpers.arrayElement(['normal','warning','critical'] as const)}, alertCount: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getGetDashboardTrendResponseMock = (overrideResponse: Partial< DashboardTrend > = {}): DashboardTrend => ({timeLabels: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), cpuData: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), memoryData: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), ...overrideResponse})

export const getGetDashboardAlertsResponseMock = (): AlertItem[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), level: faker.helpers.arrayElement(['info','warning','critical'] as const), message: faker.string.alpha({length: {min: 10, max: 20}}), source: faker.string.alpha({length: {min: 10, max: 20}}), time: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getGetServerListResponseMock = (overrideResponse: Partial< PagedResultServerItem > = {}): PagedResultServerItem => ({list: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), hostname: faker.string.alpha({length: {min: 10, max: 20}}), ip: faker.string.alpha({length: {min: 10, max: 20}}), os: faker.string.alpha({length: {min: 10, max: 20}}), cpuCores: faker.number.int({min: undefined, max: undefined}), memoryGb: faker.number.int({min: undefined, max: undefined}), status: faker.helpers.arrayElement(['running','stopped','maintenance'] as const), uptime: faker.string.alpha({length: {min: 10, max: 20}})})), total: faker.number.int({min: undefined, max: undefined}), page: faker.number.int({min: undefined, max: undefined}), pageSize: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getGetServerDetailResponseMock = (): ServerDetail => ({...{id: faker.string.alpha({length: {min: 10, max: 20}}), hostname: faker.string.alpha({length: {min: 10, max: 20}}), ip: faker.string.alpha({length: {min: 10, max: 20}}), os: faker.string.alpha({length: {min: 10, max: 20}}), cpuCores: faker.number.int({min: undefined, max: undefined}), memoryGb: faker.number.int({min: undefined, max: undefined}), status: faker.helpers.arrayElement(['running','stopped','maintenance'] as const), uptime: faker.string.alpha({length: {min: 10, max: 20}})},...{diskPartitions: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({mount: faker.string.alpha({length: {min: 10, max: 20}}), totalGb: faker.number.int({min: undefined, max: undefined}), usedGb: faker.number.int({min: undefined, max: undefined})})), networkInterfaces: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({name: faker.string.alpha({length: {min: 10, max: 20}}), ip: faker.string.alpha({length: {min: 10, max: 20}}), mac: faker.string.alpha({length: {min: 10, max: 20}})}))},})

export const getGetLogListResponseMock = (overrideResponse: Partial< PagedResultLogItem > = {}): PagedResultLogItem => ({list: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), time: `${faker.date.past().toISOString().split('.')[0]}Z`, level: faker.helpers.arrayElement(['INFO','WARN','ERROR'] as const), service: faker.string.alpha({length: {min: 10, max: 20}}), content: faker.string.alpha({length: {min: 10, max: 20}})})), total: faker.number.int({min: undefined, max: undefined}), page: faker.number.int({min: undefined, max: undefined}), pageSize: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getGetDeploymentListResponseMock = (): DeploymentItem[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), appName: faker.string.alpha({length: {min: 10, max: 20}}), version: faker.string.alpha({length: {min: 10, max: 20}}), env: faker.helpers.arrayElement(['dev','test','prod'] as const), status: faker.helpers.arrayElement(['pending','deploying','success','failed'] as const), lastDeployedAt: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getGetDeploymentHistoryResponseMock = (): DeploymentHistoryItem[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({version: faker.string.alpha({length: {min: 10, max: 20}}), operator: faker.string.alpha({length: {min: 10, max: 20}}), durationSec: faker.number.int({min: undefined, max: undefined}), status: faker.helpers.arrayElement(['success','failed'] as const), deployedAt: `${faker.date.past().toISOString().split('.')[0]}Z`})))


export const getGetDashboardMetricsMockHandler = (overrideResponse?: DashboardMetrics | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DashboardMetrics> | DashboardMetrics), options?: RequestHandlerOptions) => {
  return http.get('*/api/dashboard/metrics', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDashboardMetricsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetDashboardTrendMockHandler = (overrideResponse?: DashboardTrend | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DashboardTrend> | DashboardTrend), options?: RequestHandlerOptions) => {
  return http.get('*/api/dashboard/trend', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDashboardTrendResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetDashboardAlertsMockHandler = (overrideResponse?: AlertItem[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AlertItem[]> | AlertItem[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/dashboard/alerts', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDashboardAlertsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetServerListMockHandler = (overrideResponse?: PagedResultServerItem | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PagedResultServerItem> | PagedResultServerItem), options?: RequestHandlerOptions) => {
  return http.get('*/api/servers', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetServerListResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetServerDetailMockHandler = (overrideResponse?: ServerDetail | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ServerDetail> | ServerDetail), options?: RequestHandlerOptions) => {
  return http.get('*/api/servers/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetServerDetailResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetLogListMockHandler = (overrideResponse?: PagedResultLogItem | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PagedResultLogItem> | PagedResultLogItem), options?: RequestHandlerOptions) => {
  return http.get('*/api/logs', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetLogListResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetDeploymentListMockHandler = (overrideResponse?: DeploymentItem[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DeploymentItem[]> | DeploymentItem[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/deployments', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDeploymentListResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetDeploymentHistoryMockHandler = (overrideResponse?: DeploymentHistoryItem[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DeploymentHistoryItem[]> | DeploymentHistoryItem[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/deployments/:id/history', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDeploymentHistoryResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getDevOpsDashboardAPIMock = () => [
  getGetDashboardMetricsMockHandler(),
  getGetDashboardTrendMockHandler(),
  getGetDashboardAlertsMockHandler(),
  getGetServerListMockHandler(),
  getGetServerDetailMockHandler(),
  getGetLogListMockHandler(),
  getGetDeploymentListMockHandler(),
  getGetDeploymentHistoryMockHandler()]
