// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "your-email@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/servers": {
            "get": {
                "description": "按分页、状态筛选返回服务器列表",
                "tags": [
                    "Server"
                ],
                "summary": "获取服务器列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页条数",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "running",
                            "stopped",
                            "maintenance"
                        ],
                        "type": "string",
                        "description": "状态筛选",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.PagedResultServerItem"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.DiskPartition": {
            "type": "object",
            "properties": {
                "mount": {
                    "type": "string"
                },
                "totalGb": {
                    "type": "integer"
                },
                "usedGb": {
                    "type": "integer"
                }
            }
        },
        "model.NetworkInterface": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string"
                },
                "mac": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.PagedResultServerItem": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Server"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.Server": {
            "type": "object",
            "properties": {
                "cpuCores": {
                    "type": "integer"
                },
                "diskPartitions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.DiskPartition"
                    }
                },
                "hostname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "memoryGb": {
                    "type": "integer"
                },
                "networkInterfaces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.NetworkInterface"
                    }
                },
                "os": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "DevOps Dashboard API",
	Description:      "运维监控仪表盘后端接口",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
