/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */

export type GetDashboardTrendParams = {
/**
 * 查询最近多少小时的数据
 * @minimum 1
 * @maximum 24
 */
hours?: number;
};
