/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */
import type { GetLogListLevel } from './getLogListLevel';

export type GetLogListParams = {
page?: number;
pageSize?: number;
/**
 * 日志级别筛选
 */
level?: GetLogListLevel;
/**
 * 内容关键词模糊搜索
 */
keyword?: string;
};
