/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */
import type { GetServerListStatus } from './getServerListStatus';

export type GetServerListParams = {
/**
 * 页码，从 1 开始
 */
page?: number;
/**
 * 每页条数
 */
pageSize?: number;
/**
 * 状态筛选
 */
status?: GetServerListStatus;
};
