/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevOps Dashboard API
 * 运维监控仪表盘一期 API 规范（Spec-Driven Development）
 * OpenAPI spec version: 1.0.0
 */
import type { ServerItemStatus } from './serverItemStatus';

export interface ServerItem {
  id: string;
  hostname: string;
  ip: string;
  os: string;
  cpuCores: number;
  memoryGb: number;
  status: ServerItemStatus;
  /** 运行时长，人工可读格式 */
  uptime: string;
}
